### ISSUE TITLE
wireguard

### ISSUE THREAD

**Issue by KyleSanderson** [wfg/docker-openvpn-client#10]
Are you open to adding support for wireguard? It's much more performant with mullvad and I'd love for someone to maintain this 😸

**Comment by yacht7** [comment]
I'm certainly open to it. It's been in the back of my mind for a while now. I'll look at it later today and see how much work it'll take.

**Comment by prov3it** [comment]
> Are you open to adding support for wireguard? It's much more performant with mullvad and I'd love for someone to maintain this 😸

I have to say, having used linuxserver.io/wireguard for quiet some time now (with mullvad). I did not experience any difference in performance at all.

**Comment by yacht7** [comment]
> 
> 
> > Are you open to adding support for wireguard? It's much more performant with mullvad and I'd love for someone to maintain this 😸
> 
> I have to say, having used linuxserver.io/wireguard for quiet some time now (with mullvad). I did not experience any difference in performance at all.

I agree. I've used that image before, and I'm quite satisfied with it. If I were to build something, it would essentially be the same thing.

**Comment by nearcatch** [comment]
> > I have to say, having used linuxserver.io/wireguard for quiet some time now (with mullvad). I did not experience any difference in performance at all.
> 
> I agree. I've used that image before, and I'm quite satisfied with it. If I were to build something, it would essentially be the same thing.

The advantage to your container supporting wireguard would be not having to spin up a separate container for the proxy.

**Comment by wfg** [comment]
I don't have any plans to do this. Looking at the Linuxserver guys' image, it's [quite complex](https://github.com/linuxserver/docker-wireguard/blob/f7c9fd3d344565dcc6175aa675a12b0b7e2902ce/root/etc/cont-init.d/30-config), and not something I'm comfortable doing today.
