### ISSUE TITLE
opevpn gateway

### ISSUE THREAD

**Issue by orsa86** [wfg/docker-openvpn-client#13]
Hi,

are some additional modification required inside your container in order for below script to work?

https://github.com/ilian/docker-openvpn-gateway

I've tried to play with different iptables rules, and I believe that traffic is forwarded to the container, but afterwards I don't get any response back. If you have any hint, I would appreciate it.

**Comment by wfg** [comment]
I'm sure it's obvious by now, but I'm not sure what needs to be done here. If it's still relevant to you, please open a [discussion](https://github.com/wfg/docker-openvpn-client/discussions/new) about it.
