### ISSUE TITLE
Network_mode: service:vpn

### ISSUE THREAD

**Issue by Johan-Claesson** [wfg/docker-openvpn-client#39]
Hello, whenever I enable a container to use the vpn container as their network, the first container registers on "the wrong side" of the tunnel. 

My home net is 192.168.10.0/24, however when checking log of service1 it listens on 172.x.x.x address. 

Please assist!  ##

networks:
  my-net:
    external: 
      name: "my-net"

services:
  vpn:
    image: ghcr.io/wfg/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - KILL_SWITCH=on
      - SUBNETS=192.168.10.0/24,ip.of.dns/32,ip.of.vpn/32
      - VPN_CONFIG_FILE=xxxx.ovpn
      - VPN_LOG_LEVEL=3
      #- PROXY_USERNAME
      #- PROXY_PASSWORD
      #- HTTP_PROXY=off
      #- SOCKS_PROXY=off
      #- LISTEN_ON=0.0.0.0
    networks:
      - my-net
    ports:
      - 8083:8083/tcp #SomeService
      - 1080:1080 #SOCKS Proxy
    restart: unless-stopped
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ${APPDATA}/openvpn:/data/vpn
service1:
    image: some/service
    container_name: service1
    network_mode: container:vpn # run on the vpn network
    depends_on:
      - vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8083
    volumes:
      - ${APPDATA}/service1:/config
    restart: unless-stopped

**Comment by wfg** [comment]
I'm not sure what the problem is.
