### ISSUE TITLE
not working on Syno (restart loop)

### ISSUE THREAD

**Issue by MartinHotmann** [wfg/docker-openvpn-client#48]
Funny thing is: I already used this container some months ago and it worked flawlessly, but ATM I can't get it to work, no matter where I set it up.

```
vpn    |
vpn    | ---- Running with the following variables ----
vpn    | Kill switch: on
vpn    | HTTP proxy: off
vpn    | SOCKS proxy: off
vpn    | Proxy username secret: none
vpn    | Proxy password secret: none
vpn    | Allowing subnets: none
vpn    | Using OpenVPN log level: 3
vpn    | Listening on: none
vpn    | Using configuration file: /data/vpn/nl24.ovpn
vpn    | Creating /data/vpn/nl24.ovpn.modified and making required changes to that file.
vpn    | Changes made.
vpn    |
vpn    | Creating VPN kill switch and local routes.
vpn    | Allowing established and related connections...
vpn    | Allowing loopback connections...
vpn    | Allowing Docker network connections...
vpn    | Allowing specified subnets...
vpn    | Allowing remote servers in configuration file...
vpn    |   Using:
vpn    |     nl-24.goosevpn.com (IP: 2.58.44.66 PORT: 443 PROTOCOL: tcp)
vpn    | Allowing connections over VPN interface...
vpn    | Preventing anything else...
vpn    | iptables rules created and routes configured.
vpn    |
vpn    | Running OpenVPN client.
vpn    |
vpn    | Options error: In [CMD-LINE]:1: Error opening configuration file: /data/vpn/nl24.ovpn.modified
vpn    | Use --help for more information.
```

Notice:
`nl24.ovpn` was taken and `nl24.ovpn.modified` was created, but suddenly it cant read it. If that is a problem the container could set it's rights automatically. Actually i don't know what exactly is wrong here, but seems like:

1. permission
2. config not working (but working on another machine)

**Comment by wfg** [comment]
I guess this issue is more relevant than the other :). What is the image ID of the VPN image being used? I wonder if an update messed something up for you.

**Comment by MartinHotmann** [comment]
`sha256:2f0459a7a1468f593cffc35bb5eb24ad9a6d19445e532c70ed6cd19d32065fcb`

Thanks

**Comment by SimonvanAs** [comment]
latest works on Syno for me, maybe do a pull for the latest image? Of remove the modified OVPN file as you will see if permissions are correct as it will create a new file
