### ISSUE TITLE
Removal of FORWARDED_PORTS

### ISSUE THREAD

**Issue by HarryPeach** [wfg/docker-openvpn-client#64]
In commit 2fb155ff46e6003f95fcc91676eaa043d664d9f3 the FORWARDED_PORTS variable was removed, but I can't find a reason why.

Could this be re-added / the reason for removal clarified?

**Comment by wfg** [comment]
@HarryPeach I removed it because in my testing I found it did literally nothing.

Do you have a use case for it? I'm happy to add it back if you can explain what it was doing for you.
