### ISSUE TITLE
different socks5 proxy ips for different client containers

### ISSUE THREAD

**Issue by JeevansSP** [wfg/docker-openvpn-client#68]
I wanted to run multiple instances of client containers and have each of them have their entire network routed through a different socks5 proxy ( i will be providing each of them like this `<IP>:<port>:<user>:<pass>`), is this possible using openVPN? if so how can i do it?

**Comment by JeevansSP** [comment]
@wfg  pls help

**Comment by wfg** [comment]
Sounds like you want to run multiple instances of this image with different OpenVPN configurations. However, this is not the place for tutorials.
