### ISSUE TITLE
Push Requests?

### ISSUE THREAD

**Issue by pablos-here** [wfg/docker-openvpn-client#95]
Hi,

I've made some tweaks to my local, test set up[1].  Eventually (soon?), I'd like to figure out how to do a PR with them.  

Are PRs being accepted ... @wfg ?

Thx!

_**Reference**_

1.  Some of the tweaks I mention in #93 and #94.  I also am allowing for overriding the default reconnect timeout caps.

**Comment by wfg** [comment]
Yes, PRs are welcome. I will review the issues you linked and reply in them.
